language: node_js
dist: xenial
notifications:
  email: false
script:
  - npm exec -- run-p test lint format
after_success:
  - npm exec -- semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
