module.exports = {
  relay: [
    'assets:loaded',
    'activity:before-start',
    'activity:start',
    'interaction:start',
    'interaction:selected',
    'interaction:unselected',
    'interaction:media-consumed',
    'interaction:recognized',
    'interaction:complete',
    'pagination:paginated',
    'activity:complete',
    'stage:complete',
    'section:complete',
    'lesson:complete',
    'activity:error',
    'activity:prefetch',
    'done',
    'redo',
    'feedback:shown',
    'network-monitor:blocked',
    'network-monitor:anomaly',
  ],
}
