name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - uses: actions/checkout@v4
      - name: Give GitHub Actions access to rels_assets
        uses: webfactory/ssh-agent@v0.7.0
        with:
          log-public-key: false
          ssh-private-key: |
            ${{ secrets.RELS_GOOGLE_CLOUD }}

      - name: Set Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install modules ${{ matrix.node-version }}
        run: yarn install --frozen-lockfile

      - name: Lint and test
        run: |
          yarn lint
          yarn test
